### ISSUE TITLE
puppeteer 已停止维护，chromium下载异常

### ISSUE THREAD

**Issue by jink-e** [6677-ai/tap4-ai-crawler#2]
windows环境执行curl报错
```bash
Message: '处理https://tap4.ai站点异常，错误信息:'
Arguments: (OSError("Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip</Details></Error>.\n"),)
2024-07-17 11:17:28,457 - website_crawler.py - scrape_website - 159 - INFO - 处理https://tap4.ai用时：1 秒
```

workaround:
```python
# .venv\Lib\site-packages\pyppeteer\chromium_downloader.py
DEFAULT_DOWNLOAD_HOST = 'https://commondatastorage.googleapis.com'
```
```python
# .venv\Lib\site-packages\pyppeteer\__init__.py
__chromium_revision__ = '1181290'
```

目前 [pyppeteer](https://github.com/pyppeteer/pyppeteer) 已停止维护，是否考虑换个库？

**Comment by mundane799699** [comment]
> windows环境执行curl报错
> 
> ```shell
> Message: '处理https://tap4.ai站点异常，错误信息:'
> Arguments: (OSError("Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip</Details></Error>.\n"),)
> 2024-07-17 11:17:28,457 - website_crawler.py - scrape_website - 159 - INFO - 处理https://tap4.ai用时：1 秒
> ```
> 
> workaround:
> 
> ```python
> # .venv\Lib\site-packages\pyppeteer\chromium_downloader.py
> DEFAULT_DOWNLOAD_HOST = 'https://commondatastorage.googleapis.com'
> ```
> 
> ```python
> # .venv\Lib\site-packages\pyppeteer\__init__.py
> __chromium_revision__ = '1181290'
> ```
> 
> 目前 [pyppeteer](https://github.com/pyppeteer/pyppeteer) 已停止维护，是否考虑换个库？

pip install pyppeteer==1.0.2
亲测可用，参考：https://blog.csdn.net/weixin_44532999/article/details/138225355
